osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  GH_TOKEN:
    secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

script:
  - npm run electron:build

# deploy:
#   provider: releases
#   api_key:
#     secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb
#   file: dist_electron\*.exe
#   skip_cleanup: true
#   on:
#     tags: true

branches:
  only:
    - master

# if use yarn
# sudo: required
# before_install: # if "install" is overridden
#   # Repo for Yarn
#   - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
#   - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#   - sudo apt-get update -qq
#   - sudo apt-get install -y -qq yarn
# cache:
#   yarn: true
