# Windows Setting

image: 
  - Visual Studio 2015

platform:
  - x86

environment:
  GH_TOKEN:
    secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb
  ACCESS_TOKEN:
    secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"
  - '%USERPROFILE%\.electron'
  # - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 8 x86
  - yarn

# test_script:
#   - yarn test:unit

build_script:
  - yarn electron:build

version: 'awesome-manager-v{build}'

artifacts:
  - path: dist_electron\*.exe
    name: bin