platform:
  - x86

environment:
  GH_TOKEN:
    secure: cojifY92Y+3E21ZWUklskTlfQ1pTe6TuNK56WtaZbK1JX+OXv1m/ya1EyKxiYsUS

cache:
  - node_modules
  - lib\vue-cli-plugins\vue-cli-plugin-vuex-nedb-module-generator\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x86
  - npm install

build_script:
  - npm run electron:build

artifacts:
  - path: dist_electron\*.exe
    name: awesome-manager-v$(appveyor_build_version)

deploy:
  - provider: GitHub
    artifacts: awesome-manager-v$(appveyor_build_version)
    draft: false
    prerelease: false
    on:
      branch: master # release from master branch only
      appveyor_repo_tag: true # deploy on tag push only

test: off

branches:
  only:
    - master
