platform:
  - x86

environment:
  GH_TOKEN:
    secure: cojifY92Y+3E21ZWUklskTlfQ1pTe6TuNK56WtaZbK1JX+OXv1m/ya1EyKxiYsUS

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x86
  - npm install

build_script:
  - npm run electron:build

test: off

branches:
  only:
    - master
