platform:
  - x86

environment:
  GH_TOKEN:
    secure: cojifY92Y+3E21ZWUklskTlfQ1pTe6TuNK56WtaZbK1JX+OXv1m/ya1EyKxiYsUS

cache:
  # - node_modules
  # - lib\vue-cli-plugins\vue-cli-plugin-vuex-nedb-module-generator\node_modules
  # - '%APPDATA%\npm-cache'
  # - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x86
  - npm install

build_script:
  - npm run electron:build

artifacts:
  - path: dist_electron\*.exe
    name: bin

deploy:
  - provider: GitHub
    release: awesome-manager-v$(appveyor_build_version)
    description: "A awesome dashbaord manager powered by vue and electron"
    auth_token:
      secure: cojifY92Y+3E21ZWUklskTlfQ1pTe6TuNK56WtaZbK1JX+OXv1m/ya1EyKxiYsUS
    artifacts: bin
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true

test: off

branches:
  only:
    - master
