platform:
  - x86

environment:
  GH_TOKEN:
    secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb
  access_token:
    secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb
  APPVEYOR_REPO_TAG: true

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"
  - '%USERPROFILE%\.electron'
  - lib\vue-cli-plugins\vue-cli-plugin-vuex-nedb-module-generator\node_modules
  # - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 8 x86
  - yarn

build_script:
  - yarn electron:build

artifacts:
  - path: dist_electron\*.exe
    name: bin

# deploy:
#   - provider: GitHub
#     release: awesome-manager-v$(appveyor_build_version)
#     description: "A awesome dashbaord manager powered by vue and electron"
#     artifacts: bin
#     auth_token:
#       secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb
#     on:
#       branch: master
#       appveyor_repo_tag: true

test: off

branches:
  only:
    - master
