platform:
  - x86

environment:
  GH_TOKEN:
    secure: cojifY92Y+3E21ZWUklskTlfQ1pTe6TuNK56WtaZbK1JX+OXv1m/ya1EyKxiYsUS
  access_token:
    secure: cojifY92Y+3E21ZWUklskTlfQ1pTe6TuNK56WtaZbK1JX+OXv1m/ya1EyKxiYsUS
  appveyor_repo_tag: true

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"
  - '%USERPROFILE%\.electron'
  - lib\vue-cli-plugins\vue-cli-plugin-vuex-nedb-module-generator\node_modules
  # - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 8 x86
  - yarn

build_script:
  - yarn electron:build

artifacts:
  - path: dist_electron\*.exe
    name: bin

deploy:
  - provider: GitHub
    release: awesome-manager-v$(appveyor_build_version)
    description: "A awesome dashbaord manager powered by vue and electron"
    artifacts: bin
    auth_token:
      secure: cojifY92Y+3E21ZWUklskTlfQ1pTe6TuNK56WtaZbK1JX+OXv1m/ya1EyKxiYsUS
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true

test: off

# on_success:
#   - git config --global credential.helper store
#   - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
#   - git config --global user.email "linuxing3@qq.com"
#   - git config --global user.name "linuxing3"
#   - git commit -m "appveyor commit on success"
#   - git push origin master

branches:
  only:
    - master
